# docker/Dockerfile.frontend
FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY ./frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy remaining frontend code
COPY ./frontend/ .

EXPOSE 3000

CMD ["npm", "run", "start"]
